name = "ChainLadder"
uuid = "80b912e8-4419-4152-9910-58fcfb6515ad"
authors = ["Alec Loudenback <alecloudenback@gmail.com> and contributors"]
version = "0.1.1"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
julia = "^1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
